name: Build unsigned iOS IPA

on:
  push:
    branches:
      - main

jobs:
  ios:
    name: Build unsigned IPA
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # Inject your credentials.json from the secure secret
      - name: Inject credentials.json
        run: |
          mkdir -p assets
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" > assets/credentials.json

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build unsigned IPA
        run: flutter build ipa --no-codesign

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-runner-ipa
          path: build/ios/ipa/*.ipa
